// Code generator for Visual Transaction Builder

import { BuilderNode, BuilderEdge, OperationNode, GeneratedCode } from '@/types/builder';

export function generateCode(nodes: BuilderNode[], edges: BuilderEdge[]): GeneratedCode {
  const operationNodes = nodes.filter((n): n is OperationNode => n.type === 'operation');

  // Sort operations by dependency order (topological sort based on edges)
  const sortedOps = topologicalSort(operationNodes, edges);

  const typescript = generateTypeScript(sortedOps);
  const sql = generateSQL(sortedOps);

  return { typescript, sql };
}

function topologicalSort(operations: OperationNode[], edges: BuilderEdge[]): OperationNode[] {
  const inDegree = new Map<string, number>();
  const adjacency = new Map<string, string[]>();

  // Initialize
  operations.forEach(op => {
    inDegree.set(op.id, 0);
    adjacency.set(op.id, []);
  });

  // Build graph
  edges.forEach(edge => {
    if (inDegree.has(edge.target) && adjacency.has(edge.source)) {
      adjacency.get(edge.source)!.push(edge.target);
      inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
    }
  });

  // Find nodes with no incoming edges
  const queue: string[] = [];
  inDegree.forEach((degree, id) => {
    if (degree === 0) queue.push(id);
  });

  const sorted: OperationNode[] = [];
  while (queue.length > 0) {
    const current = queue.shift()!;
    const node = operations.find(op => op.id === current);
    if (node) sorted.push(node);

    adjacency.get(current)?.forEach(neighbor => {
      const newDegree = (inDegree.get(neighbor) || 1) - 1;
      inDegree.set(neighbor, newDegree);
      if (newDegree === 0) queue.push(neighbor);
    });
  }

  return sorted.length === operations.length ? sorted : operations;
}

function generateTypeScript(operations: OperationNode[]): string {
  const lines: string[] = [
    '// Generated by Zero-Lock Studio Transaction Builder',
    "import { Pool } from 'pg';",
    "import { DsqlSigner } from '@aws-sdk/dsql-signer';",
    '',
    'const pool = new Pool({ /* DSQL connection */ });',
    '',
    'async function executeTransaction() {',
    '  const client = await pool.connect();',
    '',
    '  // Retry loop with exponential backoff',
    '  const maxRetries = 5;',
    '  let attempt = 0;',
    '',
    '  while (attempt < maxRetries) {',
    '    try {',
    "      await client.query('BEGIN');",
    '',
  ];

  // Generate operation code
  operations.forEach((op, index) => {
    const indent = '      ';
    lines.push(`${indent}// Step ${index + 1}: ${formatOperationName(op.data.operation)} on ${op.data.table}`);
    lines.push(...generateOperationTS(op, indent));
    lines.push('');
  });

  lines.push(
    "      await client.query('COMMIT');",
    '      return { success: true };',
    '',
    '    } catch (error: unknown) {',
    '      const pgError = error as { code?: string };',
    "      await client.query('ROLLBACK');",
    '',
    "      // Check for DSQL serialization error (40001)",
    "      if (pgError.code === '40001') {",
    '        attempt++;',
    '        if (attempt >= maxRetries) {',
    "          throw new Error('Max retries exceeded');",
    '        }',
    '',
    '        // Exponential backoff with jitter',
    '        const baseDelay = 50;',
    '        const maxDelay = 5000;',
    '        const delay = Math.min(baseDelay * Math.pow(2, attempt), maxDelay);',
    '        const jitter = delay * (0.5 + Math.random() * 0.5);',
    '        await new Promise(r => setTimeout(r, jitter));',
    '        continue;',
    '      }',
    '',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  client.release();',
    '}',
    '',
    'executeTransaction().catch(console.error);',
  );

  return lines.join('\n');
}

function generateOperationTS(op: OperationNode, indent: string): string[] {
  const lines: string[] = [];
  const { operation, table, columns, whereClause, setValues } = op.data;

  switch (operation) {
    case 'select':
      lines.push(`${indent}const ${sanitizeVar(op.id)} = await client.query(`);
      lines.push(`${indent}  'SELECT ${columns.join(', ')} FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''}'`);
      lines.push(`${indent});`);
      break;

    case 'select_for_update':
      lines.push(`${indent}const ${sanitizeVar(op.id)} = await client.query(`);
      lines.push(`${indent}  'SELECT ${columns.join(', ')} FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''} FOR UPDATE'`);
      lines.push(`${indent});`);
      break;

    case 'update':
      const setClause = setValues
        ? Object.entries(setValues).map(([col, val]) => `${col} = ${val}`).join(', ')
        : columns.map(c => `${c} = $${c}`).join(', ');
      lines.push(`${indent}await client.query(`);
      lines.push(`${indent}  'UPDATE ${table} SET ${setClause}${whereClause ? ` WHERE ${whereClause}` : ''}'`);
      lines.push(`${indent});`);
      break;

    case 'insert':
      lines.push(`${indent}await client.query(`);
      lines.push(`${indent}  'INSERT INTO ${table} (${columns.join(', ')}) VALUES (${columns.map((_, i) => `$${i + 1}`).join(', ')})'`);
      lines.push(`${indent});`);
      break;

    case 'delete':
      lines.push(`${indent}await client.query(`);
      lines.push(`${indent}  'DELETE FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''}'`);
      lines.push(`${indent});`);
      break;
  }

  return lines;
}

function generateSQL(operations: OperationNode[]): string {
  const lines: string[] = [
    '-- Generated by Zero-Lock Studio Transaction Builder',
    '-- Note: Add retry logic in application code for SQLSTATE 40001',
    '',
    'BEGIN;',
    '',
  ];

  operations.forEach((op, index) => {
    lines.push(`-- Step ${index + 1}: ${formatOperationName(op.data.operation)}`);
    lines.push(generateOperationSQL(op));
    lines.push('');
  });

  lines.push('COMMIT;');

  return lines.join('\n');
}

function generateOperationSQL(op: OperationNode): string {
  const { operation, table, columns, whereClause, setValues } = op.data;

  switch (operation) {
    case 'select':
      return `SELECT ${columns.join(', ')} FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''};`;

    case 'select_for_update':
      return `SELECT ${columns.join(', ')} FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''} FOR UPDATE;`;

    case 'update':
      const setClause = setValues
        ? Object.entries(setValues).map(([col, val]) => `${col} = ${val}`).join(', ')
        : columns.map(c => `${c} = :${c}`).join(', ');
      return `UPDATE ${table} SET ${setClause}${whereClause ? ` WHERE ${whereClause}` : ''};`;

    case 'insert':
      return `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${columns.map(c => `:${c}`).join(', ')});`;

    case 'delete':
      return `DELETE FROM ${table}${whereClause ? ` WHERE ${whereClause}` : ''};`;

    default:
      return '';
  }
}

function formatOperationName(op: string): string {
  return op.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function sanitizeVar(id: string): string {
  return id.replace(/-/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
}
